### ISSUE TITLE
MP>=50, vì dùng xong còn 0 mana vẫn ok. Lần sau nên thêm phần nếu ko đủ MP thì ghi ko đủ MP thì hay hơn

### ISSUE THREAD

**Issue by GuardianOfGods** [daoxuanvinh992000/btvn-java_hit_2019#10]
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/c83f5018a71bec6adf51dce5b2ab67ca67b15317/BTVN-BU%E1%BB%94I%204/b%C3%A0i%202/Knight.java#L52

**Comment by xuanhieu2903** [comment]
Vâng để e sửa ạ
