### ISSUE TITLE
Bài 4: Nhấn vào để xem chi tiết

### ISSUE THREAD

**Issue by GuardianOfGods** [daoxuanvinh992000/btvn-java_hit_2019#13]
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/c83f5018a71bec6adf51dce5b2ab67ca67b15317/BTVN-BU%E1%BB%94I%204/b%C3%A0i%204/Fight.java#L1-L54

**Comment by GuardianOfGods** [comment]
- Lỗi 1: giống lỗi bài 3

**Comment by GuardianOfGods** [comment]
- Lỗi 2: Dòng này là n[0] > và n[1] >
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/c83f5018a71bec6adf51dce5b2ab67ca67b15317/BTVN-BU%E1%BB%94I%204/b%C3%A0i%204/Fight.java#L41

**Comment by GuardianOfGods** [comment]
- Lỗi 3: Để như này sẽ không hiển thị info sau trận đấu nữa
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/c83f5018a71bec6adf51dce5b2ab67ca67b15317/BTVN-BU%E1%BB%94I%204/b%C3%A0i%204/Fight.java#L31-L37

**Comment by GuardianOfGods** [comment]
- Lỗi 4: Còn rất nhiều lỗi khác, do không áp dụng được OOP vào bài nên xảy ra rất nhiều hạn chế.

**Comment by xuanhieu2903** [comment]
Vâng a
