### ISSUE TITLE
Thế này dùng vòng for làm gì nhỉ =)). Lần sau in ra a[2] là đủ rồi 

### ISSUE THREAD

**Issue by GuardianOfGods** [daoxuanvinh992000/btvn-java_hit_2019#6]
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/955e0859cb25f25240ead630466db913e7e6b013/BTVN%20BUOI2/BTVN1.java#L28-L32

**Comment by xuanhieu2903** [comment]
😅😅😅 e quên mất cứ tưởng a[i]
