### ISSUE TITLE
Nhấn vào đây để xem chi tiết bài 3

### ISSUE THREAD

**Issue by GuardianOfGods** [daoxuanvinh992000/btvn-java_hit_2019#7]
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/955e0859cb25f25240ead630466db913e7e6b013/BTVN%20BUOI2/BTVN3.java#L7-L14
-> Vì java ko có tham chiếu, tham trị nên ta ko truyền a vào hàm trực tiếp, vì thế phần này sẽ phải đặt a làm biến toàn cục. Viết như phía dưới. Mỗi khi nhập mảng đồng thời tạo mới mảng luôn (vẫn dùng chung mảng a[]).
![image](https://user-images.githubusercontent.com/52252046/66899368-05023e00-f025-11e9-8937-11b362c36e6a.png)
----------------------------------------------------------------------------------------------------------
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/955e0859cb25f25240ead630466db913e7e6b013/BTVN%20BUOI2/BTVN3.java#L16-L22
-> Hãy dùng a.length ở đây thay vì truyền n vào, vì khi xóa hay thêm mảng, mảng sẽ ko còn n phần tử nữa. Tuy nhiên nó sẽ hiển thị ra các ô chưa được gán số và nó sẽ tự động gán bằng số 0.
![image](https://user-images.githubusercontent.com/52252046/66899865-e18bc300-f025-11e9-8346-4ab16d84e438.png)
----------------------------------------------------------------------------------------------------------
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/955e0859cb25f25240ead630466db913e7e6b013/BTVN%20BUOI2/BTVN3.java#L47-L52
-> Đây ko phải đảo mảng nhé :)). Đây là hiển thị mảng ngược nhé 🥇 
----------------------------------------------------------------------------------------------------------
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/955e0859cb25f25240ead630466db913e7e6b013/BTVN%20BUOI2/BTVN3.java#L71-L79
-> Sau cho n vào phần nhập mảng nhé. Khai báo biến toàn cục như bên trên a làm.
----------------------------------------------------------------------------------------------------------

**Comment by xuanhieu2903** [comment]
Vâng
