### ISSUE TITLE
Bài 2: Phần này sau nên ghi là ShowMP nhé, hàm thì nên viết hoa các chữ cái đầu

### ISSUE THREAD

**Issue by GuardianOfGods** [daoxuanvinh992000/btvn-java_hit_2019#9]
https://github.com/daoxuanvinh992000/btvn-java_hit_2019/blob/98d6f32cfbe5cd4a2c7839a2d519a5480db5b58c/BTVN-bu%E1%BB%95i3/bai%202/dog.java#L16

**Comment by xuanhieu2903** [comment]
vâng a. chắc e viết nhầm
